In [2]:
import pandas as pd

df = pd.read_csv(r"E:\Monali\Class\machineLearning\ML\17Apr\houseprice.csv")
df.head()

bath  balcony  price  total_sqft_int  bhk  price_per_sqft  \
0   3.0      2.0  150.0          1672.0    3     8971.291866   
1   3.0      3.0  149.0          1750.0    3     8514.285714   
2   3.0      2.0  150.0          1750.0    3     8571.428571   
3   2.0      2.0   40.0          1250.0    2     3200.000000   
4   2.0      2.0   83.0          1200.0    2     6916.666667   

   area_typeSuper built-up  Area  area_typeBuilt-up  Area  \
0                              1                        0   
1                              0                        1   
2                              1                        0   
3                              1                        0   
4                              0                        0   

   area_typePlot  Area  availability_Ready To Move  ...  \
0                    0                           1  ...   
1                    0                           1  ...   
2                    0                           1  ...   
3                    0                           1  ...   
4                    1                           1  ...   

   location_Kalena Agrahara  location_Horamavu Agara  location_Vidyaranyapura  \
0                         0                        0                        0   
1                         0                        0                        0   
2                         0                        0                        0   
3                         0                        0                        0   
4                         0                        0                        0   

   location_BTM 2nd Stage  location_Hebbal Kempapura  location_Hosur Road  \
0                       0                          0                    0   
1                       0                          0                    0   
2                       0                          0                    0   
3                       0                          0                    0   
4                       0                          0                    0   

   location_Horamavu Banaswadi  location_Domlur  location_Mahadevpura  \
0                            0                0                     0   
1                            0                0                     0   
2                            0                0                     0   
3                            0                0                     0   
4                            0                0                     0   

   location_Tumkur Road  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  

[5 rows x 108 columns]

In [5]:
#Separating dependent & independant variable

X = df.drop('price', axis=1)
y = df['price']

print('Shape of X = ', X.shape)

print('Shape of y = ', y.shape)

Shape of X =  (7120, 107)
Shape of y =  (7120,)


In [6]:
#Splitting train & test sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=51)

print('Shape of X_train = ', X_train.shape)

print('Shape of y_train = ', y_train.shape)

print('Shape of X_test = ', X_test.shape)

print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


In [11]:
# applying Fearure scaling to the data

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

sc.fit(X_train)

X_train = sc.transform(X_train)

X_test = sc.transform(X_test)

In [12]:
# Train Machine Learning Model

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train, y_train)

LinearRegression()

In [13]:
lr.coef_

array([-5.70206143e+00, -1.25679916e+00,  8.27341833e+01, -1.44906911e+01,
        5.75662723e+01,  1.88468905e-01, -1.72593897e+00, -4.51058311e+00,
       -2.22589244e+00, -4.28978455e+00, -2.44590976e+00,  5.40246226e-01,
       -1.03633400e+00,  1.43064873e+00, -6.25029424e-02, -1.51548783e+00,
       -2.14422789e-01,  2.16244155e+00, -1.48710228e+00,  1.95250816e+00,
       -3.10761125e+00, -1.28138668e+00, -1.01367155e+00,  1.37968545e-02,
        1.10383858e+00,  1.26497611e+00, -3.52405517e+00, -1.21398741e+00,
       -5.04622019e-01,  1.46299181e+00, -5.50064233e-01, -8.46468162e-02,
        6.84882188e-01, -1.39849820e+00, -1.94761710e-02, -1.57716300e+00,
        4.20886278e-01,  8.03443207e-01,  2.99182164e+00,  3.86430413e-03,
        1.05037261e-01,  2.89115612e-01, -3.16916626e-01,  1.05625868e+00,
       -1.39649279e+00, -3.10533604e+00,  1.01764011e-01, -7.49672917e-02,
       -8.03271555e-01, -1.27061856e+00, -8.54046164e-01,  2.64566484e-01,
        9.10688839e-01, -

In [14]:
lr.intercept_

95.08027299859552

In [15]:
#predicted values
lr.predict(X_test)

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [17]:
for i in lr.predict(X_test):
    print(i)

76.90661876274689
15.250053772034661
113.68281650437899
84.97120278643094
18.86195385466506
41.35169220908411
48.30628622157567
87.62581952962415
108.92520656325864
63.92292956279888
102.97508258367536
323.7974660105091
300.6816174388597
255.64649371030615
173.75695500153614
51.23319799116218
105.9398283896275
95.06937539749471
170.36755225452163
56.397687632792675
71.57011279476234
43.775832591705644
28.60379947129239
58.61165683707421
226.42100021468227
387.45013281178456
-11.255810595802231
94.79010890144869
174.0034094602103
171.50862895380016
50.06515681448013
45.73842855316503
277.33098780752266
329.9153005717407
102.37000742606733
52.43157020432958
63.294180212649835
107.05612918161245
1.365058055963587
101.88855662343953
61.51977602852115
13.8367560845587
85.50804865676486
82.55244899478717
76.75235497752927
54.44770873622724
85.15835767319784
84.04528755903117
94.21663526275202
31.732201210391466
52.59214567544765
-14.702468352396593
47.72335266551094
102.03758789392167
176.11

In [18]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [19]:
# Accuracy

lr.score(X_test, y_test)

0.7903837092682255

# using lasso & Ridge regression

In [20]:
from sklearn.linear_model import Ridge, Lasso

rd = Ridge()

rd.fit(X_train,y_train)

rd.score(X_test, y_test)

0.790568637433663

In [21]:
ls = Lasso()

ls.fit(X_train,y_train)
ls.score(X_test, y_test)

0.8036373003525775

In [22]:
# setting alpha =2 in ridge
rd2 = Ridge(alpha = 2)

rd2.fit(X_train,y_train)

rd2.score(X_test, y_test)


0.7907530260397941

In [23]:
ls2 = Lasso(alpha=2)

ls2.fit(X_train,y_train)

ls2.score(X_test, y_test)

0.8160181533703601

In [24]:
ls3 = Lasso(alpha = 50)

ls3.fit(X_train,y_train)

ls3.score(X_test, y_test)

0.5838161771389456

In [25]:
#Root Mean Squre Error

y_pred = lr.predict(X_test)

y_pred

array([ 76.90661876,  15.25005377, 113.6828165 , ...,  21.30296864,
        71.43462962, 230.0414626 ])

In [26]:
y_test

2435     80.00
3113     40.00
426     120.00
1124     79.00
1161     45.00
         ...  
2078     28.34
6855     84.00
4381     32.00
3862     63.00
43      180.00
Name: price, Length: 1424, dtype: float64

In [27]:
# mean Square error

from sklearn.metrics import mean_squared_error 
import numpy as np

mse = mean_squared_error(y_test, y_pred)

rmse = np.sqrt(mse)

print('MSE = ', mse)

print('RMSE = ', rmse)

MSE =  4211.806905823321
RMSE =  64.898435311056
